### ISSUE TITLE
Error when parsing comment after final closing bracket

### ISSUE THREAD

**Issue by sfraczek** [besok/graphviz-rust#12]
I have a graph that I want to parse which ends like this:
```dot
   node_425887->node_425122
} // end G
```
And I get a parsing error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "    --> 8685:3\n     |\n8685 | } // end G\n     |   ^---\n     |\n     = expected EOI"', src/main.rs:7:62

**Comment by besok** [comment]
Will take a look shortly
