### ISSUE TITLE
Release new version for into-attr-derive

### ISSUE THREAD

**Issue by aminya** [besok/graphviz-rust#17]
into-attr-derive is still using dot-generator v0.1.0 on creates.io. A new release will fix this
https://github.com/besok/graphviz-rust/blob/173c98f4e9d9d763c08c0a31abbc512ef56cb137/into-attr-derive/Cargo.toml

Likewise, all the dependent crates need to be updated.

**Comment by besok** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [update ver](https://trello.com/c/bK2Iwqtx/916-update-ver)
