### ISSUE TITLE
Dot parser is forbidding characters it should not within the "double quoted string" variant of IDs.

### ISSUE THREAD

**Issue by BeldrothTheGold** [besok/graphviz-rust#21]
The parser is forbidding many characters it should not within the  "double quoted string" variant of IDs.

FROM https://graphviz.org/doc/info/lang.html:

An ID is one of the following:

- Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits([0-9]), not beginning with a digit;
- a numeral [-]?(.[0-9]⁺ | [0-9]⁺(.[0-9]*)? );
- **any double-quoted string ("...") possibly containing escaped quotes (\")¹;**
- an HTML string (<...>).
... 

1. In quoted strings in DOT, the only escaped character is double-quote ". That is, in quoted strings, the dyad \\" is converted to " all other characters are left unchanged. In particular, \\ remains \\. Layout engines may apply additional escape sequences.

--

This graph doesn't parse yet it is valid dot. 
```dot
digraph graph_test {
  start [
    label="This shouln't error"
  ];
  end [
    label="End"
  ];
  start-> end;
} 
```
```
 --> 4:11
  |
4 |     label="This shouln't error"
  |           ^---
  |
  = expected id
```

--- it looks like the issue is here:
```
char = _{
    !("\"" | "\\" | "\'") ~ ANY
    | "\\" ~ ("\"" | "\'" |  "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    // TODO: the following option is only valid for some attributes: https://graphviz.org/docs/attr-types/escString/
    | "\\" ~ ("G" | "N" | "E" | "H" | "T" | "L")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}
```

**Comment by ScottCUSA** [comment]
Another example:

test.dot:
```dot
digraph graph_test {
  start [
    label="context.set('This \\\"shouldn\'t\\\" error');"
  ];
  end [
    label="End"
  ];
  start-> end;
}
 ```
The above graph rendered to a PNG using graphviz
```
> dot -V
dot - graphviz version 2.49.3 (0)
> dot -Tpng -O test.dot
> 
```
![image](https://github.com/besok/graphviz-rust/assets/106980485/30ae2007-ca5a-4242-b9df-f2d73e69965e)

It looks like this allows the above to work.

``` pest
char = {
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t" | "'" )
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
    // TODO: the following option is only valid for some attributes: https://graphviz.org/docs/attr-types/escString/
    | "\\" ~ ("G" | "N" | "E" | "H" | "T" | "L")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}
```

**Comment by besok** [comment]
Yeah, it seems to be a hole in the grammar.
