### ISSUE TITLE
png parsing

### ISSUE THREAD

**Issue by uglyoldbob** [besok/graphviz-rust#25]
I am trying to generate a png from a graph and am running into a problem.
The exec function returns Option<String> and it looks like String cannot properly represent the contents of a png file.
When I write the contents of the string to a file, it is not a valid png file.

```
let graph_png = graphviz_rust::exec(
                self.graph.clone(),
                &mut PrinterContext::default(),
                vec![graphviz_rust::cmd::Format::Png.into()],
            )
            .unwrap()
            
            .as_bytes()
            .to_vec();
std::fs::write("./generated.png", &graph_png).unwrap();
```

**Comment by uglyoldbob** [comment]
I created a pull request with a solution for this problem.
https://github.com/besok/graphviz-rust/pull/26

**Comment by besok** [comment]
Sorry for the late response. I am on vacation and I did not see it unfortunately. Thanks for the issue and the pr
