### ISSUE TITLE
`NodeId` does not derive `Eq`

### ISSUE THREAD

**Issue by acidghost** [besok/graphviz-rust#27]
I'm wondering why `NodeId` does not derive `Eq`: https://github.com/besok/graphviz-rust/blob/d9e1ea03ae432e90ce670801fd71c7b31102a771/dot-structures/src/lib.rs#L51-L52

Both `Id` and `Port` derive `Eq` so `NodeId` can derive it too.

**Comment by besok** [comment]
Ah yeah, sure. 
I think the partial eq was enough for me but yeah this seems easy delivarable

**Comment by besok** [comment]
Ah yeah, sure. 
I think the partial eq was enough for me but yeah this seems easy delivarable

**Comment by besok** [comment]
added
