### ISSUE TITLE
Add support for printing nodes with multiple attributes on separate lines. 

### ISSUE THREAD

**Issue by ScottCUSA** [besok/graphviz-rust#32]
I would like to add support for printing attributes for nodes with multiple attributes on separate lines. 

I will submit a PR for this shortly. Thanks for your consideration!

For example: 
```
digraph multi {
  a[shape=square]
  aa[
    color=blue,
    shape=Mrecord
  ]
  subgraph v {
    aaa[shape=square]
    aaaa[
      color=red,
      shape=Mrecord
    ]
    aaa -> aaaa [label=FALSE]
  }
  a -> aa [label=TRUE,color=green]
}
```

![image](https://github.com/besok/graphviz-rust/assets/106980485/6e2d2941-c8f6-4a3b-abf8-cdb73819276d)

**Comment by besok** [comment]
Hi. Sure 😊
