### ISSUE TITLE
Provide example usage of SubgraphAttributes

### ISSUE THREAD

**Issue by sloganking** [besok/graphviz-rust#38]
```rust
let subgraph_nodes: Vec<Stmt> = //...
subgraph!(subgraph_id.as_u128(), subgraph_nodes)
```

Works for me, but my subgraphs have no color or border. I want to assign `SubgraphAttributes::label` in order to attempt to make the subgraphs visible. What is the valid syntax for that?

**Comment by besok** [comment]
Yeah. Truly, there are no macros associated with graph attr. I created an [issue](https://github.com/besok/graphviz-rust/issues/39) for that.

Meanwhile,

In case, if you want to have a border for the subgraph, then the [clusters](https://graphviz.org/Gallery/directed/cluster.html) need to be used. Thus,  the `id` should have the prefix `cluster`.

For now, you can manually create graph attributes like this:
```rust
     let attrs = GraphAttributes::new("graph", vec![
            SubgraphAttributes::style("dotted".to_owned()),
            SubgraphAttributes::color(color_name::green),
            SubgraphAttributes::label("sandwich".to_owned()),
        ]);
```
 or using `attr!`:
```rust
        let attrs = GraphAttributes::new("graph", vec![
            attr!("style","bold"),
            attr!("color","green"),
            attr!("label", "sandwich"),
        ]);
```

The complete example:
```rust
    #[test]
    fn issue_with_node_test() {
        let attrs = GraphAttributes::new("graph", vec![
            SubgraphAttributes::style("dotted".to_owned()),
            SubgraphAttributes::color(color_name::green),
            SubgraphAttributes::label("sandwich".to_owned()),
        ]);
        let food =  subgraph!("cluster_sandwich";
            edge!(node_id!("bread") => node_id!("ham") => node_id!("salat")),
            attrs
        );
        let g = graph!(strict di id!("t"); edge!(node_id!("food") => food));
        let string = g.print(&mut Default::default());
        println!("{}",string);
    }
```
[prints](https://dreampuf.github.io/GraphvizOnline/#strict%20digraph%20t%20%7B%0A%20%20food%20-%3E%20subgraph%20cluster_sandwich%20%7B%0A%20%20%20%20bread%20-%3E%20ham%20-%3E%20salat%0A%20%20%20%20graph%5Bstyle%3Dbold%2Ccolor%3Dgreen%2Clabel%3Dsandwich%5D%0A%20%20%7D%0A%7D) :
```dot
strict digraph t {
  food -> subgraph cluster_sandwich {
    bread -> ham -> salat
    graph[style=bold,color=green,label=sandwich]
  }
}
```

**Comment by besok** [comment]
I added the `attrs!` macro.
The example now can look like this:
```rust
        let food =  subgraph!("cluster_sandwich";
            edge!(node_id!("bread") => node_id!("ham") => node_id!("salat")),
            attrs!(graph; attr!("style", "bold"), attr!("color","green"), attr!("label", "sandwich"))
        );
```
