### ISSUE TITLE
Graph should be visible

### ISSUE THREAD

**Issue by anon767** [besok/graphviz-rust#5]
The Graph enum and its fields should be visible.
For reasons where the printer interface does not satisfy more complex use-cases, e.g. interact with a graph database or such stuff

**Comment by besok** [comment]
I agree, that the visibility of the graph is vital for handling complex cases.
But at the moment the structures are public and you can easily obtain the access to the fields like that:
```rust
          let mut g = graph!(id!("id");;
          
          match g {
            Graph::Graph { id, strict, stmts } => {}
            Graph::DiGraph { id, strict, stmts } => {
                match stmts.get(0){
                    None => {}
                    Some(Stmt::Node(node)) => {}
                    Some(stm) => {}
                  }
              }
          }
```

Or do you mean another visibility?

**Comment by anon767** [comment]
Hm correct me if I'm wrong, but shouldn't dot_structures be public here:
https://github.com/besok/graphviz-rust/blob/master/src/lib.rs#L81

```
pub use dot_structures::*;
```

Im not able to access it when using the crate :(

**Comment by besok** [comment]
well. Perhaps, it can be useful but honestly, you should have an access to the structures if I don't misunderstand it.
Have you had a look at the following repo? https://github.com/besok/test-graphviz-rust.git

**Comment by anon767** [comment]
interesting. It works with graphviz-rust 0.1.2 but it does not work with graphviz-rust 0.2.0

**Comment by besok** [comment]
Indeed. I will give a look in the evening.

**Comment by besok** [comment]
it turned out there were no references to the underling crates in the main crate so therefore I added them [evidenly](https://github.com/besok/graphviz-rust/blob/9c49d143297c0a42efadf7356f6fedd4cee80b65/src/lib.rs#L79)
It should work properly in the new version.

**Comment by anon767** [comment]
perfect :) thanks
