### ISSUE TITLE
dot pest update

### ISSUE THREAD

**Issue by yashmasani** [besok/graphviz-rust#6]
Hey!
First of all, thanks for the awesome library!
I am trying to create a uml diagram for my db and have issues with the parse function specifically on the code
`<tr><td>address_id: int</td></tr>`
I suspect its the dot.pest file the needs to be updated to handle special characters like : or _
thanks

**Comment by besok** [comment]
Hey. Thanks. 
I see. The problem is in HTML tags namely `< >`. They are delivered with a bug. I will fix it next week probably
